apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    field.cattle.io/publicEndpoints: '[{"addresses":["172.19.18.8"],"port":32613,"protocol":"TCP","serviceName":"p-6stkv-pipeline:helloserver-service","allNodes":true},{"addresses":["172.19.18.17"],"port":80,"protocol":"HTTP","serviceName":"p-6stkv-pipeline:ingress-d2e36cb9a5d0eb6b11bf3b605f74462a","ingressName":"p-6stkv-pipeline:test","hostname":"test.p-6stkv-pipeline.172.19.18.17.xip.io","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"helloserver"},"name":"example-helloserver","namespace":"p-6stkv-pipeline"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"helloserver"}},"template":{"metadata":{"labels":{"app":"helloserver"}},"spec":{"containers":[{"image":"127.0.0.1:34934/example-helloserver:4","name":"helloserver","ports":[{"containerPort":80}]}],"imagePullSecrets":[{"name":"pipeline-docker-registry"}]}}}}
  creationTimestamp: 2018-10-11T19:44:42Z
  generation: 12
  labels:
    app: helloserver
  name: example-helloserver
  namespace: p-6stkv-pipeline
  resourceVersion: "19413"
  selfLink: /apis/apps/v1beta2/namespaces/p-6stkv-pipeline/deployments/example-helloserver
  uid: 194ac0f5-cd8e-11e8-acc5-0a4739f0d052
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helloserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloserver
    spec:
      containers:
      - image: 127.0.0.1:34934/example-helloserver:4
        imagePullPolicy: IfNotPresent
        name: helloserver
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: pipeline-docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: 2018-10-11T19:44:42Z
    lastUpdateTime: 2018-10-11T21:01:03Z
    message: ReplicaSet "example-helloserver-68bcc5cdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-10-11T21:02:23Z
    lastUpdateTime: 2018-10-11T21:02:23Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 12
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
